export const usersMock = [
  {
    id: 1,
    firstName: 'Kaila',
    lastName: 'Chase',
    email: 'kaila@chase.co',
    avatar: 'https://api.adorable.io/avatars/285/kaila',
  },
  {
    id: 2,
    firstName: 'Lorenzo',
    lastName: 'Worthington',
    email: 'lorenzo@worthington.co',
    avatar: 'https://api.adorable.io/avatars/285/lorenzo',
  },
  {
    id: 3,
    firstName: 'Gillian',
    lastName: 'Thornton',
    email: 'gillian@thornton.co',
    avatar: 'https://api.adorable.io/avatars/285/gillian',
  },
  {
    id: 4,
    firstName: 'Atticus',
    lastName: 'Cuevas',
    email: 'Atticus@Cuevas.co',
    avatar: 'https://api.adorable.io/avatars/285/atticus',
  },
  {
    id: 5,
    firstName: 'Steven',
    lastName: 'Hendrix',
    email: 'steven@hendrix.co',
    avatar: 'https://api.adorable.io/avatars/285/steven',
  },
  {
    id: 6,
    firstName: 'Cory',
    lastName: 'Waters',
    email: 'cory@waters.co',
    avatar: 'https://api.adorable.io/avatars/285/cory',
  },
  {
    id: 7,
    firstName: 'Joni',
    lastName: 'Martins',
    email: 'joni@martins.co',
    avatar: 'https://api.adorable.io/avatars/285/joni',
  },
  {
    id: 8,
    firstName: 'Heather',
    lastName: 'Ellis',
    email: 'heather@ellis.co',
    avatar: 'https://api.adorable.io/avatars/285/heather',
  },
  {
    id: 9,
    firstName: 'Caius',
    lastName: 'Mcclain',
    email: 'caius@mcclain.co',
    avatar: 'https://api.adorable.io/avatars/285/caius',
  },
  {
    id: 10,
    firstName: 'Tarik',
    lastName: 'Piper',
    email: 'rarik@piper.co',
    avatar: 'https://api.adorable.io/avatars/285/tarik',
  },
];
